name: build and push to Docker Hub

on: [push]

env:
  base_image: lamatriz/pytorch:1.12.0-1.6.0-439-deepspeed
  prefix_image_name: lamatriz
  
jobs:
  build:
    runs-on: [k8s-linux]

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 
          DOCKERHUB_TOKEN: ${{ secrets.DOCEKRHUB_TOKEN }}
          ecr: false
      - name: build a docker image
        run: docker build --no-cache --build-arg base_image=${base_image} -t ${prefix_image_name}/hccl_demo:${GITHUB_SHA} .
